name: native_image_plugin
description: It's a simple flutter plugin to get image data from native side.
version: 0.1.1
author: Kevin Zhan <zhanymx@gmail.com>
homepage: http://zymx.tech

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: tech.zymx.nativeimageplugin
    pluginClass: NativeImagePlugin
